name: event_authentication
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/VHCBlade/event_authentication

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:

  crypto: ^3.0.3
  encrypt: ^5.0.1

  event_db: ^0.1.8

  tuple: ^2.0.1

dev_dependencies:
  event_bloc_tester: ^0.1.4

  lints: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^4.0.0
